package com.snslib;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "People".
 */
@Entity(nameInDb = "People")
public class Person {

    @Id
    private Long id;
    private short name;

    @Property(nameInDb = "_sex")
    private String sex;

    @Generated
    public Person() {
    }

    public Person(Long id) {
        this.id = id;
    }

    @Generated
    public Person(Long id, short name, String sex) {
        this.id = id;
        this.name = name;
        this.sex = sex;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public short getName() {
        return name;
    }

    public void setName(short name) {
        this.name = name;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

}
